---
- name: Ensure syslog User Exists
  user:
    name: syslog
    shell: /usr/sbin/nologin
    home: /nonexistent
  ignore_errors: true

- name: Install FRR
  package:
    name: frr

- name: Enable BGP Daemon in FRR
  lineinfile:
    path: /etc/frr/daemons
    regexp: "^bgpd"
    line: bgpd=yes

- name: Enable BFD Daemon in FRR
  lineinfile:
    path: /etc/frr/daemons
    regexp: "^bfdd"
    line: bfdd=yes
  when: enable_bfd | bool

- name: Template FRR Configuration File
  vars:
    bgp_peers: "{{ groups['container_runners'] }}"
  template:
    src: templates/frr.conf.j2
    dest: /etc/frr/frr.conf

- name: Restart / Enable FRR Service
  systemd_service:
    name: frr
    enabled: true
    state: restarted
    daemon_reload: true
